micronaut:
# Object Storage with Oracle Cloud Object Storage
  object-storage:
    oracle-cloud:
      images:
        bucket: ${BUCKET_NAME}
        namespace: ${BUCKET_NAMESPACE}
# Metrics via Oracle Cloud Application Monitoring
  metrics:
    enabled: true
    binders:
      files:
        enabled: true
      jdbc:
        enabled: true
      jvm:
        enabled: true
      logback:
        enabled: true
      processor:
        enabled: true
      uptime:
        enabled: true
      web:
        enabled: true
    export:
      oraclecloud:
        compartmentId: ${COMPARTMENT_ID}
        enabled: true
        namespace: cloudworld2022demo
# Database via Oracle Cloud Autonomous Transaction Processing
datasources:
  default:
    ocid: ${ATP_OCID}
    wallet-password: ${ATP_WALLET_PASSWORD}
    username: ${ATP_USERNAME}
    password: ${ATP_PASSWORD}
    dialect: oracle
flyway:
  datasources:
    default:
      enabled: true
# Tracing via Oracle Cloud Application Performance Monitoring (APM)
otel:
  traces:
    exporter: zipkin
  exporter:
    zipkin:
      endpoint: ${APM_ENDPOINT}/20200101/observations/public-span?dataFormat=zipkin&dataFormatVersion=2&dataKey=${APM_KEY}
