micronaut:
  server:
    thread-selection: IO
  router:
    static-resources:
      images:
        enabled: true
        paths: classpath:images
        mapping: /images/**
netty:
  default:
    allocator:
      max-order: 3
