micronaut:
  application:
    name: aws
  object-storage:
    aws:
      images:
        bucket: cloudworld-demo
datasources:
  default:
    driverClassName: com.mysql.cj.jdbc.Driver
    db-type: mysql
    username: ${username}
    password: ${password}
    url: "jdbc:mysql://${host}:${port}/micronaut"
flyway:
  datasources:
    default:
      enabled: true
otel:
  traces:
    exporter: otlp
    propagator: tracecontext, baggage, xray
    exclusions: /health
netty:
  default:
    allocator:
      max-order: 3
